import type { RegistrationAddress } from './interfaces';

export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  CART: '/cart',
  LOGIN: '/login',
  REGISTRATION: '/registration',
  PROFILE: '/profile',
  CATALOG: '/catalog',
  LOGOUT: '/logout',
  NOTFOUND: '*',
  PRODUCT: 'product/:id',
  CONTACTS: '/contacts',
} as const;

export const allowedCountries = new Set([
  'Austria',
  'Belgium',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hungary',
  'Ireland',
  'Italy',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Netherlands',
  'Poland',
  'Portugal',
  'Romania',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
]);

export const allowedCountriesArray = [...allowedCountries];
export const countryToAlpha2 = {
  Austria: 'AT',
  Belgium: 'BE',
  Bulgaria: 'BG',
  Croatia: 'HR',
  Cyprus: 'CY',
  'Czech Republic': 'CZ',
  Denmark: 'DK',
  Estonia: 'EE',
  Finland: 'FI',
  France: 'FR',
  Germany: 'DE',
  Greece: 'GR',
  Hungary: 'HU',
  Ireland: 'IE',
  Italy: 'IT',
  Latvia: 'LV',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Malta: 'MT',
  Netherlands: 'NL',
  Poland: 'PL',
  Portugal: 'PT',
  Romania: 'RO',
  Slovakia: 'SK',
  Slovenia: 'SI',
  Spain: 'ES',
  Sweden: 'SE',
};

export const postalCodePatterns: Record<string, RegExp> = {
  Austria: /^\d{4}$/,
  Belgium: /^\d{4}$/,
  Bulgaria: /^\d{4}$/,
  Croatia: /^\d{5}$/,
  Cyprus: /^\d{4}$/,
  'Czech Republic': /^\d{3}\s?\d{2}$/,
  Denmark: /^\d{4}$/,
  Estonia: /^\d{5}$/,
  Finland: /^\d{5}$/,
  France: /^\d{5}$/,
  Germany: /^\d{5}$/,
  Greece: /^\d{5}$/,
  Hungary: /^\d{4}$/,
  Ireland: /^[A-Za-z]\d[\dA-Za-z]?\s?\d[A-Za-z]{2}$/,
  Italy: /^\d{5}$/,
  Latvia: /^\d{4}$/,
  Lithuania: /^\d{5}$/,
  Luxembourg: /^\d{4}$/,
  Malta: /^[A-Z]{3}\s?\d{4}$/,
  Netherlands: /^\d{4}\s?[A-Z]{2}$/,
  Poland: /^\d{2}-\d{3}$/,
  Portugal: /^\d{4}-\d{3}$/,
  Romania: /^\d{6}$/,
  Slovakia: /^\d{3}\s?\d{2}$/,
  Slovenia: /^\d{4}$/,
  Spain: /^\d{5}$/,
  Sweden: /^\d{3}\s?\d{2}$/,
};
export const defaultAddressForm: RegistrationAddress = {
  country: '',
  city: '',
  street: '',
  house: '',
  postalCode: '',
  asDefaultShippingAddress: false,
  billingAddressFlag: false,
  asDefaultBillingAddress: false,
};

export const FILTER_CONSTANTS = {
  PRICE: {
    MIN: 0,
    MAX: 30000,
    STEP: 1000,
    DIVIDE: 100,
  },
  HEIGHT: {
    MIN: 0,
    MAX: 100,
    STEP: 5,
  },
} as const;

export const ITEMS_PER_PAGE = 12;
