name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
          reviewers: max0n4ik, ElizabethMedvedeva, m-bond91
          max-num-of-reviewers: 2
